function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of stairs x data
%  YMATRIX1:  matrix of stairs y data

%  Auto-generated by MATLAB on 18-Feb-2026 16:48:53

% Create figure
figure('Tag','ScopePrintToFigure','Color',[1 1 1],...
    'OuterPosition',[673 299 576 489]);

% uicontainer currently does not support code generation, enter 'doc uicontainer' for correct input syntax
% In order to generate code for uicontainer, you may use GUIDE. Enter 'doc guide' for more information
% uicontainer(...);

% uicontainer currently does not support code generation, enter 'doc uicontainer' for correct input syntax
% In order to generate code for uicontainer, you may use GUIDE. Enter 'doc guide' for more information
% uicontainer(...);

% uipanel currently does not support code generation, enter 'doc uipanel' for correct input syntax
% In order to generate code for uipanel, you may use GUIDE. Enter 'doc guide' for more information
% uipanel(...);

% Create axes
axes1 = axes('Tag','DisplayAxes1_RealMag');
hold(axes1,'on');
colororder([0.0666666666666667 0.443137254901961 0.745098039215686;0.866666666666667 0.329411764705882 0;0.929411764705882 0.694117647058824 0.125490196078431;0.52156862745098 0.0862745098039216 0.819607843137255;0.231372549019608 0.666666666666667 0.196078431372549;0.184313725490196 0.745098039215686 0.937254901960784;0.819607843137255 0.0156862745098039 0.545098039215686]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create multiple stair objects using matrix input to stairs
stairs1 = stairs(X1,YMatrix1,'LineWidth',2);
set(stairs1(1),'DisplayName','Low-Pass Filter (Discrete or Continuous)4:1',...
    'Tag','DisplayLine1',...
    'Color',[0 0 0]);
set(stairs1(2),'DisplayName','Low-Pass Filter (Discrete or Continuous)4:2',...
    'Tag','DisplayLine2',...
    'Color',[0.149019607843137 0.549019607843137 0.866666666666667]);

% Create xlabel
xlabel(' ');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 600.000000000003]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-2.82275 15.47477]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'ClippingStyle','rectangle','FontSize',8,'GridAlpha',0.4,...
    'GridColor',[0 0 0],'TickLabelInterpreter','none','XGrid','on','YGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Units','pixels',...
    'Position',[278.333339502411 341.833326012396 257.999993830919 32.4999991655349],...
    'Interpreter','none',...
    'FontSize',8,...
    'EdgeColor',[0 0 0]);

% Create text
text('Tag','TimeOffsetStatus','Units','pixels','VerticalAlignment','bottom',...
    'FontSize',8,...
    'Position',[0 0 0],...
    'Visible','on');

